env:
  type: pusht

policy:
  type: flow_matching
  device: cuda

vis:
  num_rollouts: 1
  action_dim_names: ["pos_x", "pos_y"]

vector_field:
  action_dims: [0, 1]
  grid_size: 25

noise_to_action:
  action_dims: [0, 1]
  axis_limits: [[-1, 1], [-1, 1]]

composed_sequence_sampler:
    scoring_metric:
      metric_type: mode_distance
    num_action_samples: 20

show: False
seed: 6

# python src/lerobot/scripts/uncertainty/visualize_composed_seq_sampler.py --config=configs/flow_matching/visualize_composed_seq_sampler/pusht.yaml --policy.path=outputs/train/flow_matching/pusht/checkpoints/last/pretrained_model_migrated