dataset:
  repo_id: lerobot/aloha_sim_transfer_cube_human

env:
  type: aloha
  task: AlohaTransferCube-v0

eval_uncert_est:
  n_episodes: 50
  uncert_est_methods: [cross_bayesian]
  perturbation_config:
    enable: True
    static: False
    allowed_area: [0.7, 0.5]
    patch_color: [255, 0, 0]
  id_failure_seeds_path: outputs/failure_seeds/aloha_transfer_id_failure_seeds/failure_seeds.json
  ood_failure_seeds_path: outputs/failure_seeds/aloha_transfer_ood_failure_seeds/failure_seeds.json

uncertainty_sampler:
  composed_cross_bayesian_sampler:
    scorer_type: ensemble
    ensemble_model_path: outputs/train/flow_matching_aloha_transfer_02/checkpoints/055000/pretrained_model
    scoring_metric: likelihood
    num_action_samples: 5
  cross_bayesian_sampler:
    scorer_type: ensemble
    ensemble_model_path: outputs/train/flow_matching_aloha_transfer_02/checkpoints/055000/pretrained_model
    scoring_metric: inter_vel_diff
    velocity_eval_times: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95]
    num_action_samples: 5
  composed_sequence_sampler:
    scoring_metric: terminal_vel_norm


job_name: terminal_vel_norm_aloha

# python lerobot/scripts/flow_matching/eval_uncertainty_estimation.py --config=configs/flow_matching/eval_uncertainty_estimation/aloha_transfer.yaml --policy.path=outputs/train/flow_matching_aloha_transfer/checkpoints/040000/pretrained_model