dataset:
  repo_id: lerobot/aloha_sim_transfer_cube_human

env:
  type: aloha
  task: AlohaTransferCube-v0

eval_uncert_est:
  n_episodes: 50
  uncert_est_methods: [cross_laplace]
  perturbation_config:
    enable: True
    static: False
    allowed_area: [0.7, 0.5]
    patch_color: [255, 0, 0]
  id_failure_seeds_path: outputs/failure_seeds/aloha_transfer_id_failure_seeds/failure_seeds.json
  ood_failure_seeds_path: outputs/failure_seeds/aloha_transfer_ood_failure_seeds/failure_seeds.json

uncertainty_sampler:
  cross_laplace_sampler:
    laplace_scope: velocity_last
    calib_fraction: 1.0
    batch_size: 1
  cross_ensemble_sampler:
    scorer_model_path: outputs/train/flow_matching_aloha_transfer_02/checkpoints/055000/pretrained_model

job_name: velocity_last_50_episodes

# python lerobot/scripts/flow_matching/eval_uncertainty_estimation.py --config=configs/flow_matching/eval_uncertainty_estimation/aloha_transfer.yaml --policy.path=outputs/train/flow_matching_aloha_transfer/checkpoints/040000/pretrained_model