dataset:
  repo_id: HuggingFaceVLA/libero

env:
  type: libero
  task: libero_10

eval_uncert_est:
  n_episodes: 50
  uncert_est_methods: [cross_bayesian]
  domains: [id]

uncertainty_sampler:
  composed_cross_bayesian_sampler:
    scorer_type: ensemble
    ensemble_model_path: outputs/train/flow_matching/libero_spatial_02/checkpoints/035000/pretrained_model_migrated
    scoring_metric:
      metric_type: mode_distance
    num_action_seq_samples: 5
  composed_sequence_sampler:
    scoring_metric:
      metric_type: mode_distance
    num_action_seq_samples: 5
  cross_bayesian_sampler:
    scorer_type: ensemble
    ensemble_model_path: outputs/train/flow_matching/libero_spatial_02/checkpoints/035000/pretrained_model_migrated
    scoring_metric:
      metric_type: mode_distance
    num_action_seq_samples: 5
  entropy_sampler:
    num_action_seq_samples: 1000

seed: 42

# python src/lerobot/scripts/flow_matching/eval_uncertainty_estimation.py --config=configs/flow_matching/eval_uncertainty_estimation/libero.yaml --policy.path=outputs/train/flow_matching/libero_spatial/checkpoints/035000/pretrained_model_migrated