dataset:
  repo_id: lerobot/libero_spatial_one_bowl

env:
  type: libero
  task: LiberoEnv-v0
  benchmark: libero_spatial

eval_uncert_est:
  n_episodes: 500
  uncert_est_methods: [composed_sequence, composed_cross_bayesian]

uncertainty_sampler:
  composed_cross_bayesian_sampler:
    scorer_type: ensemble
    ensemble_model_path: outputs/train/flow_matching_libero_spatial_02/checkpoints/035000/pretrained_model
    scoring_metric:
      metric_type: inter_vel_diff
    num_action_seq_samples: 5
  composed_sequence_sampler:
    scoring_metric:
      metric_type: inter_vel_diff
    num_action_seq_samples: 5
  cross_bayesian_sampler:
    scorer_type: ensemble
    ensemble_model_path: outputs/train/flow_matching_libero_spatial_02/checkpoints/035000/pretrained_model
    scoring_metric:
      metric_type: inter_vel_diff
    num_action_seq_samples: 5

seed: 112200

# python lerobot/scripts/flow_matching/eval_uncertainty_estimation.py --config=configs/flow_matching/eval_uncertainty_estimation/libero.yaml --policy.path=outputs/train/flow_matching_libero_spatial/checkpoints/035000/pretrained_model