dataset:
  repo_id: lerobot/pusht

env:
  type: pusht

eval_uncert_est:
  n_episodes: 20
  uncert_est_methods: [composed_sequence]
  collapse_success_failure: True

uncertainty_sampler:
  composed_cross_bayesian_sampler:
    scorer_type: ensemble
    ensemble_model_path: outputs/train/flow_matching_pusht_02/checkpoints/200000/pretrained_model
    scoring_metric:
      metric_type: inter_vel_diff
    num_action_seq_samples: 5
  composed_sequence_sampler:
    scoring_metric:
      metric_type: inter_vel_diff
    num_action_seq_samples: 1
  cross_bayesian_sampler:
    scorer_type: ensemble
    ensemble_model_path: outputs/train/flow_matching_pusht_02/checkpoints/200000/pretrained_model
    scoring_metric:
      metric_type: inter_vel_diff
    num_action_seq_samples: 5

seed: 42

# python lerobot/scripts/flow_matching/eval_uncertainty_estimation.py --config=configs/flow_matching/eval_uncertainty_estimation/pusht.yaml --policy.path=outputs/train/flow_matching_pusht/checkpoints/200000/pretrained_model