dataset:
  repo_id: lerobot/pusht

env:
  type: pusht
  perturbation:
    patch_color: [0, 0, 0]

eval_uncert_est:
  uncert_est_methods: [cross_likelihood_laplace]
  perturbation_config:
    enable: True
    static: False
  collapse_success_failure: True

uncertainty_sampler:
  cross_likelihood_laplace_sampler:
    laplace_scope: velocity_last
    calib_fraction: 1.0
    batch_size: 10

  cross_likelihood_ensemble_sampler:
    scorer_model_path: outputs/train/flow_matching_pusht_02/checkpoints/200000/pretrained_model
    use_vel_score: True

# python lerobot/scripts/flow_matching/eval_uncertainty_estimation.py --config=configs/flow_matching/eval_uncertainty_estimation/pusht.yaml --policy.path=outputs/train/flow_matching_pusht/checkpoints/200000/pretrained_model