dataset:
  repo_id: lerobot/pusht

env:
  type: pusht

eval_uncert_est:
  n_episodes: 20
  uncert_est_methods: [composed_sequence]
  collapse_success_failure: True
  perturbation_config:
    enable: True
    static: False
    patch_color: [0, 0, 0]

uncertainty_sampler:
  composed_sequence_sampler:
    scoring_metric: terminal_vel_norm
  
  cross_laplace_sampler:
    laplace_scope: both
    calib_fraction: 1.0
    batch_size: 10
    scoring_metric: intermediate_vel_diff

  cross_ensemble_sampler:
    scorer_model_path: outputs/train/flow_matching_pusht_02/checkpoints/200000/pretrained_model
    scoring_metric: intermediate_vel_diff

# python lerobot/scripts/flow_matching/eval_uncertainty_estimation.py --config=configs/flow_matching/eval_uncertainty_estimation/pusht.yaml --policy.path=outputs/train/flow_matching_pusht/checkpoints/200000/pretrained_model