env:
  type: aloha
  task: AlohaTransferCube-v0

eval:
  batch_size: 10
  n_episodes: 100

# python src/lerobot/scripts/eval.py --config=configs/flow_matching/eval/aloha_transfer.yaml --policy.path=outputs/train/flow_matching/aloha_transfer/checkpoints/050000/pretrained_model_migrated