env:
  type: pusht

eval:
  batch_size: 10
  n_episodes: 100

# python lerobot/scripts/eval.py --config=configs/flow_matching/eval/pusht.yaml --policy.path=outputs/train/flow_matching_pusht/checkpoints/last/pretrained_model