env:
  type: pusht

eval:
  batch_size: 10
  n_episodes: 10

# python src/lerobot/scripts/eval.py --config=configs/flow_matching/eval/pusht.yaml --policy.path=outputs/train/flow_matching_pusht_02/checkpoints/last/pretrained_model_migrated