env:
  type: libero
  task: libero_10
  task_ids: [0]

policy:
  type: smolvla
  device: cuda

vis:
  num_rollouts: 1
  action_dim_names: [
    "ee_pos_x", "ee_pos_y", "ee_pos_z", "ee_rot_x",
    "ee_rot_y", "ee_rot_z", "gripper_open"
  ]

vector_field:
  action_dims: [0, 1]
  grid_size: 20
  min_action: -2
  max_action: 2

noise_to_action:
  action_dims: [0, 1]
  axis_limits: [[-2, 2], [-2, 2]]

composed_sequence_sampler:
    scoring_metric:
      metric_type: mode_distance
    num_action_samples: 25

show: False
seed: 6

# python src/lerobot/scripts/uncertainty/visualize_composed_seq_sampler.py --config=configs/smolvla/visualize_composed_seq_sampler/libero.yaml --policy.path=outputs/train/smolvla/libero_filtered_finetuned/checkpoints/015000/pretrained_model