dataset:
  repo_id: lerobot/pusht

env:
  type: pusht
  perturbation:
    enable: False

policy:
  type: flow_matching
  device: cuda

vis:
  vis_types: [action_seq]

uncertainty_sampler:
  cross_likelihood_laplace_sampler:
    laplace_scope: both
    calib_fraction: 1.0
    batch_size: 10

n_laplace_models: 3

# python lerobot/scripts/flow_matching/visualize_laplace.py --config=configs/flow_matching/visualize_laplace/pusht.yaml --policy.path=outputs/train/flow_matching_pusht/checkpoints/last/pretrained_model