env:
  type: libero
  task: LiberoEnv-v0
  benchmark: libero_spatial

policy:
  type: flow_matching
  device: cuda

vis:
  num_rollouts: 1
  # start_step: 60
  action_dim_names: ["ee_pos_x", "ee_pos_y", "ee_pos_z",
                     "ee_rot_x", "ee_rot_y", "ee_rot_z",
                     "gripper_open"]

vector_field:
  action_dims: [0, 1]
  action_steps: [0]
  grid_size: 20

ensemble_sampler:
  scorer_model_path: outputs/train/flow_matching_libero_spatial_02/checkpoints/035000/pretrained_model
  num_action_seq_samples: 25
  scoring_metric: mode_distance
  velocity_eval_times: [0.0, 0.1, 0.2]

show: False
seed: 58

# python lerobot/scripts/flow_matching/visualize_ensemble_uncertainty_estimation.py --config=configs/flow_matching/visualize_ensemble/libero.yaml --policy.path=outputs/train/flow_matching_libero_spatial/checkpoints/035000/pretrained_model