dataset:
  repo_id: HuggingFaceVLA/libero

policy:
  type: smolvla
  device: cuda
  repo_id: bensturgis/smolvla-libero

env:
  type: libero
  task: libero_10

eval:
  batch_size: 1
  n_episodes: 5

output_dir: outputs/train/smolvla_libero_scratch
steps: 200000
batch_size: 64
eval_freq: 5000
val_ratio: 0.05
save_freq: 10000
seed: 22110026
wandb:
  enable: true

# python src/lerobot/scripts/train.py --config=configs/smolvla/train/libero_scratch.yaml