dataset:
  repo_id: HuggingFaceVLA/libero
  libero_tasks: {
    libero_spatial: [],
    libero_object: [],
    libero_goal: [],
    libero_10: [0, 4, 7, 8, 9]
  }

policy:
  type: smolvla
  device: cuda
  repo_id: bensturgis/smolvla-libero-5-tasks-scratch-with-vision-02

env:
  type: libero
  task: libero_10
  task_ids: [0, 4, 7, 8, 9]

eval:
  batch_size: 1
  n_episodes: 5

output_dir: outputs/train/smolvla/libero_5_tasks_scratch_with_vision_02
steps: 100000
batch_size: 40
eval_freq: 10000
val_ratio: 0.05
save_freq: 10000
seed: 18
wandb:
  enable: true

# python src/lerobot/scripts/train.py --config=configs/smolvla/train/libero_scratch.yaml