dataset:
  repo_id: HuggingFaceVLA/libero
  libero_tasks: {
    libero_spatial: [],
    libero_object: [],
    libero_goal: [],
    libero_10: [0]
  }

policy:
  type: smolvla
  device: cuda
  repo_id: bensturgis/smolvla-libero-filtered

env:
  type: libero
  task: libero_spatial
  task_ids: [0, 1, 2]

eval:
  batch_size: 1
  n_episodes: 5

output_dir: outputs/train/test
steps: 200000
batch_size: 20
eval_freq: 5000
val_ratio: 0.05
save_freq: 10000
seed: 17021012
wandb:
  enable: true

# python src/lerobot/scripts/train.py --config=configs/smolvla/train/libero_scratch.yaml