dataset:
  repo_id: HuggingFaceVLA/libero
  libero_tasks: {
      libero_spatial: [],
      libero_object: [],
      libero_goal: [],
      libero_10: [0, 4, 7, 8, 9]
    }

policy:
  type: smolvla
  device: cuda
  repo_id: bensturgis/smolvla-libero-aop-only-02

env:
  type: libero
  task: libero_10
  task_ids: [0, 4, 7, 8, 9]

eval:
  batch_size: 1
  n_episodes: 10

reinitialize_selected_layers: True

output_dir: outputs/train/smolvla/libero_aop_only_02
steps: 50000
batch_size: 48
eval_freq: 2500
save_freq: 2500
enable_val_loss: False
seed: 3222
wandb:
  enable: true
job_name: smolvla_libero_aop_only_02

# python src/lerobot/scripts/train.py --config=configs/smolvla/train/libero_finetuning.yaml --policy.path=outputs/train/smolvla/libero_finetuned_01/checkpoints/010000/pretrained_model --policy.repo_id=bensturgis/smolvla-libero-aop-only-02