dataset:
  repo_id: HuggingFaceVLA/libero
  libero_tasks: {
      libero_spatial: [],
      libero_object: [],
      libero_goal: [],
      libero_10: [0, 4, 7, 8, 9]
    }

policy:
  type: smolvla
  device: cuda
  repo_id: bensturgis/smolvla-libero-finetuned-03

env:
  type: libero
  task: libero_10
  task_ids: [0, 4, 7, 8, 9]

eval:
  batch_size: 1
  n_episodes: 10

output_dir: outputs/train/smolvla/libero_finetuned_03
steps: 50000
batch_size: 48
eval_freq: 5000
save_freq: 5000
enable_val_loss: False
seed: 916831
wandb:
  enable: true
job_name: smolvla_libero_finetuned_03

# python src/lerobot/scripts/train.py --config=configs/smolvla/train/libero_finetuning.yaml --policy.path=outputs/train/smolvla/libero_base/checkpoints/030000/pretrained_model --policy.repo_id=bensturgis/smolvla-libero-finetuned-03