dataset:
  repo_id: HuggingFaceVLA/libero
  libero_tasks: {
    libero_spatial: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    libero_object: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    libero_goal: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    libero_10: [1, 2, 3, 5, 6]
  }

policy:
  type: smolvla
  device: cuda
  repo_id: bensturgis/test

env:
  type: libero
  task: libero_10
  task_ids: [1, 2, 3, 5, 6]

eval:
  batch_size: 1
  n_episodes: 5

output_dir: outputs/train/test
steps: 100000
batch_size: 40
eval_freq: 10000
val_ratio: 0.05
save_freq: 10000
seed: 18
wandb:
  enable: true

# python src/lerobot/scripts/train.py --config=configs/smolvla/train/libero_scratch.yaml