dataset:
  repo_id: HuggingFaceVLA/libero
  libero_tasks: {
      libero_spatial: [],
      libero_object: [],
      libero_goal: [],
      libero_10: [0, 4, 7, 8, 9]
    }


policy:
  type: smolvla
  device: cuda
  repo_id: bensturgis/smolvla-libero-finetuning-with-aop-reinitialization-02

env:
  type: libero
  task: libero_10
  task_ids: [0, 4, 7, 8, 9]

eval:
  batch_size: 1
  n_episodes: 10

reinitialize_selected_layers: True

output_dir: outputs/train/smolvla/libero_finetuning_with_aop_reinitialization_02
steps: 100000
batch_size: 48
eval_freq: 5000
save_freq: 5000
val_ratio: 0.05
seed: 1111
wandb:
  enable: true

# python src/lerobot/scripts/train.py --config=configs/smolvla/train/libero_finetuning.yaml --policy.path=outputs/train/smolvla/libero_filtered_base_unfreezed_vision_horizon_50/checkpoints/020000/pretrained_model --policy.repo_id=bensturgis/smolvla-libero-finetuning-with-aop-reinitialization-02