dataset:
  repo_id: lerobot/pusht

env:
  type: pusht

policy:
  type: smolvla
  device: cuda
  repo_id: bensturgis/smolvla-pusht

output_dir: outputs/train/smolvla/pusht
batch_size: 64
steps: 200000
eval_freq: 5000
val_ratio: 0.05
save_freq: 20000
seed: 42
wandb:
  enable: true

# python src/lerobot/scripts/train.py --config=configs/smolvla/train/pusht.yaml