dataset:
  repo_id: HuggingFaceVLA/libero
  libero_tasks: {
    libero_spatial: [],
    libero_object: [],
    libero_goal: [],
    libero_10: [0, 4, 7, 8, 9]
  }

env:
  type: libero
  task: libero_10
  task_ids: [0, 4, 7, 8, 9]

eval_uncert_est:
  n_episodes: 50
  uncert_est_methods: [cross_bayesian]
  domains: [id]

uncertainty_sampler:
  composed_cross_bayesian_sampler:
    scorer_type: ensemble
    ensemble_model_path: outputs/train/smolvla/libero_5_tasks_scratch_02/checkpoints/020000/pretrained_model
    laplace_scopes: [action_out_proj, expert_last]
    scoring_metric:
      metric_type: mode_distance
    num_action_samples: 20
  composed_sequence_sampler:
    scoring_metric:
      metric_type: mode_distance
    num_action_samples: 25
  cross_bayesian_sampler:
    scorer_type: ensemble
    ensemble_model_path: outputs/train/smolvla/libero_finetuning_with_aop_reinitialization_02/checkpoints/005000/pretrained_model
    scoring_metric:
      metric_type: mode_distance
    num_action_samples: 25

seed: 111
job_name: finetuned_laplace_fitting

# python src/lerobot/scripts/uncertainty/eval_uncertainty_estimation.py --config=configs/smolvla/eval_uncertainty_estimation/libero.yaml --policy.path=outputs/train/smolvla/libero_finetuning_with_aop_reinitialization/checkpoints/005000/pretrained_model