dataset:
  repo_id: HuggingFaceVLA/libero
  libero_tasks: {
    libero_spatial: [],
    libero_object: [],
    libero_goal: [],
    libero_10: [0, 3, 4, 7, 8]
  }

env:
  type: libero
  task: libero_10
  task_ids: [0, 1]

eval_uncert_est:
  n_episodes: 50
  uncert_est_methods: [cross_bayesian]
  domains: [id]

uncertainty_sampler:
  composed_cross_bayesian_sampler:
    scorer_type: laplace
    laplace_scopes: [action_out_proj, expert_last]
    scoring_metric:
      metric_type: mode_distance
    num_action_samples: 5
  composed_sequence_sampler:
    scoring_metric:
      metric_type: mode_distance
    num_action_samples: 5
  cross_bayesian_sampler:
    scorer_type: laplace
    laplace_scopes: [action_out_proj, expert_last]
    scoring_metric:
      metric_type: terminal_vel_norm
    num_action_samples: 5

seed: 120120

# python src/lerobot/scripts/uncertainty/eval_uncertainty_estimation.py --config=configs/smolvla/eval_uncertainty_estimation/libero.yaml --policy.path=outputs/train/smolvla/libero_filtered_finetuned/checkpoints/005000/pretrained_model