env:
  type: aloha
  task: AlohaTransferCube-v0
  perturbation:
    enable: True
    static: False
    allowed_area: [0.7, 0.5]

eval:
  batch_size: 10
  n_episodes: 10

num_failure_seeds: 250

# python lerobot/scripts/find_failure_seeds.py --config=configs/flow_matching/find_failure_seeds/aloha_transfer.yaml --policy.path=outputs/train/flow_matching_aloha_transfer/checkpoints/040000/pretrained_model