# Choose from "action_seq", "noise_to_action", "flows" and "vector_field"
vis_types: [action_seq, flows, vector_field]
show: False
seed: 40

env:
  type: libero
  task: libero_10
  task_ids: [2]

policy:
  type: smolvla
  device: cuda

vis:
  num_rollouts: 2
  action_dim_names: [
    "ee_pos_x", "ee_pos_y", "ee_pos_z", "ee_rot_x",
    "ee_rot_y", "ee_rot_z", "gripper_open"
  ]

vector_field:
  action_dims: [1, 2]
  grid_size: 20
  min_action: -2
  max_action: 2

noise_to_action:
  action_dims: [1, 2]
  axis_limits: [[-1.5, 1.5], [-1.5, 1.5]]
  num_samples: 1

flows:
  action_dims: [1, 2]
  axis_limits: [[-2, 2], [-2, 2]]
  num_paths: 25


# python src/lerobot/scripts/visualize_flow_matching.py --config=configs/smolvla/visualize/libero.yaml --policy.path=outputs/train/smolvla/libero_filtered_finetuned_unfreezed_vision_horizon_50/checkpoints/005000/pretrained_model