dataset:
  repo_id: lerobot/libero_spatial_one_bowl

env:
  type: libero
  task: LiberoEnv-v0
  benchmark: libero_spatial

fiper_data_recorder:
  num_uncertainty_sequences: 128
  ode_eval_times: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95]
  terminal_vel_eval_times: [0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3]
  ensemble_model_path: outputs/train/flow_matching_libero_spatial_02/checkpoints/035000/pretrained_model

n_calib_episodes: 100
n_test_episodes: 250

seed: 28

# python lerobot/scripts/flow_matching/record_fiper_data.py --config=configs/flow_matching/record_fiper_data/libero.yaml --policy.path=outputs/train/flow_matching_libero_spatial/checkpoints/035000/pretrained_model